title = "Bhairavi Muralidharan"
baseURL = "https://bhairavi-m.github.io/"
theme = "researcher"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]
enableEmoji = true
math = false  # enable KaTeX (https://katex.org/) globally

[params]
  author = "Bhairavi Muralidharan"
  description = "Bhairavi Muralidharan's web resume"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "Built with a theme by Olivier Roques"
    url = "https://github.com/ojroques/hugo-researcher"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 2

[markup]
  defaultMarkdownHandler = 'blackFriday'
    [markup.blackFriday]
      hrefTargetBlank = true
